"""provledger.testing.calibration — calibration items generated BY CONSTRUCTION
(phase 8 Task 1, FL-041): the corpus swaps (truth declared next to the variant),
programmatic negatives (2:2 unrelated twins → "none") and partial links
(2:1 → one pair, one stranger). No model labels anything here."""
import json
from pathlib import Path

import pytest

from orchestrator import graph_api as g
from orchestrator.testing import calibration as cal
from orchestrator.testing import harness
from orchestrator.testing import heuristic_arbiter as ha

CASES = harness.default_corpus()


def _truth_kind(item):
    return cal.truth_kind(item)


def test_row_context_is_optional_and_ignored_by_the_matcher():
    r = g.Row(1, None, "k", "function", "pkg.m.f", "pkg/m.py", 1, 2, "s", None, True)
    assert r.context is None
    r2 = g.Row(1, None, "k", "function", "pkg.m.f", "pkg/m.py", 1, 2, "s", None, True, context="    1  def f(): ...")
    assert r2.context.startswith("    1  ")
    d = cal.row_to_dict(r2)
    assert d["context"] == r2.context and cal.row_from_dict(d).context == r2.context


def test_harness_validates_the_truth_mapping(tmp_path):
    case = tmp_path / "bad_case"
    (case / "base").mkdir(parents=True)
    (case / "variants" / "swap_two_similar" / "before").mkdir(parents=True)
    (case / "variants" / "swap_two_similar" / "after").mkdir(parents=True)
    (case / "expect.toml").write_text(
        '[case]\nname = "bad_case"\nsymbols = ["pkg.m.a"]\n[variants]\n'
        'swap_two_similar = { identity = "ambiguous", symbols = ["pkg.m.a", "pkg.m.b"], '
        'truth = { "pkg.m.a" = "pkg.m.x", "pkg.m.NOPE" = "pkg.m.y" } }\n')
    with pytest.raises(ValueError, match="truth"):
        harness.load_case(case)


def test_every_corpus_swap_declares_its_truth_by_construction():
    cases = harness.iter_cases(CASES)
    assert len(cases) == 3
    for c in cases:
        spec = c.expect["variants"]["swap_two_similar"]
        truth = spec["truth"]
        assert set(truth) == set(spec["symbols"]), c.name
        assert len(set(truth.values())) == len(truth), c.name


def test_light_extractor_agrees_with_the_corpus_symbols():
    for c in harness.iter_cases(CASES):
        rows = cal.extract_rows(c.base)
        qns = {r.qualified_name for r in rows}
        assert set(c.expect["case"]["symbols"]) <= qns, (c.name, qns)
        assert all(r.node_type in ("function", "method", "class") and r.struct_sig for r in rows)
        assert all(r.context and r.file_path for r in rows)


def test_generate_from_corpus_yields_one_pairs_item_per_case():
    items = cal.generate_from_corpus(CASES)
    assert len(items) == 3
    for it in items:
        assert it["source"].startswith("corpus:") and it["source"].endswith("/swap_two_similar")
        assert it["labelled_by"] == "construction" and it["ambiguity"]["layer"] == "struct_sig"
        prev = {r["qualified_name"] for r in it["ambiguity"]["prev"]}
        cur = {r["qualified_name"] for r in it["ambiguity"]["cur"]}
        pairs = it["truth"]["pairs"]
        assert {p for p, _ in pairs} == prev and {c for _, c in pairs} == cur
        assert _truth_kind(it) == "pairs"
        assert all(r["context"] for r in it["ambiguity"]["prev"] + it["ambiguity"]["cur"])
        assert all(r["node_key"] for r in it["ambiguity"]["prev"])


def test_generate_negatives_every_case_has_none_and_partial_items():
    items = cal.generate_negatives(CASES)
    by_case: dict[str, list] = {}
    for it in items:
        assert it["source"].startswith("negative:") and it["labelled_by"] == "construction"
        assert _truth_kind(it) in ("none", "partial")
        by_case.setdefault(it["source"].split(":", 1)[1].split("/")[0], []).append(it)
    assert set(by_case) == {"basic_pipeline", "class_methods", "two_modules"}
    for name, its in by_case.items():
        kinds = {_truth_kind(i) for i in its}
        assert len(its) >= 2 and kinds == {"none", "partial"}, (name, kinds)
    layers = {it["ambiguity"]["layer"] for it in items}
    assert layers == {"struct_sig", "dataflow_sig"}
    ids = [it["id"] for it in items]
    assert len(ids) == len(set(ids))
    partial = next(i for i in items if _truth_kind(i) == "partial")
    prev = {r["qualified_name"] for r in partial["ambiguity"]["prev"]}
    cur = {r["qualified_name"] for r in partial["ambiguity"]["cur"]}
    assert len(partial["truth"]["pairs"]) == 1 and len(prev) == 1 and len(cur) == 2
    none = next(i for i in items if _truth_kind(i) == "none")
    assert len(none["ambiguity"]["prev"]) == 2 and len(none["ambiguity"]["cur"]) == 2


def test_generate_swaps_pairs_by_construction():
    items = cal.generate_swaps(CASES)
    assert len(items) >= 10
    for it in items:
        assert it["source"].startswith("swap:") and _truth_kind(it) == "pairs"
        prev = [r["qualified_name"] for r in it["ambiguity"]["prev"]]
        assert len(prev) == 2 and len(it["truth"]["pairs"]) == 2


def test_merge_dedupes_and_prefers_the_labelled_copy():
    a = cal.generate_from_corpus(CASES)
    unlabelled = [dict(it, truth=None, labelled_by=None, id="live-" + it["id"]) for it in a]
    merged = cal.merge(unlabelled, a)
    assert len(merged) == 3 and all(it["truth"] for it in merged)
    assert len(cal.merge(a, a, cal.generate_negatives(CASES))) == len(a) + len(cal.generate_negatives(CASES))


def test_stats_counts_layer_source_truth_and_node_type():
    items = cal.merge(cal.generate_from_corpus(CASES), cal.generate_negatives(CASES), cal.generate_swaps(CASES))
    s = cal.stats(items)
    assert s["n"] == len(items) >= 40
    assert s["by_truth"]["pairs"] >= 15 and s["by_truth"]["none"] >= 10 and s["by_truth"]["partial"] >= 5
    assert s["by_truth"].get("unlabelled", 0) == 0
    assert set(s["by_layer"]) == {"struct_sig", "dataflow_sig"}
    assert s["by_source"]["corpus"] == 3 and s["by_source"]["negative"] >= 8 and s["by_source"]["swap"] >= 10
    assert "function" in s["by_node_type"] and "method" in s["by_node_type"]
    assert sum(s["by_truth"].values()) == s["n"] == sum(s["by_layer"].values())


def test_generated_set_is_a_valid_calibration_file_and_the_heuristic_is_no_longer_perfect(tmp_path):
    items = cal.merge(cal.generate_from_corpus(CASES), cal.generate_negatives(CASES), cal.generate_swaps(CASES))
    p = tmp_path / "calib.json"
    p.write_text(json.dumps({"version": cal.VERSION, "items": items}))
    cal.load_calibration(p)
    rep = cal.run(ha.HeuristicArbiter(), p, n_runs=2, out_dir=tmp_path / "eval")
    assert rep.consistency == 1.0 and rep.evidence_ok
    assert rep.coverage > 0 and rep.n_truth == len(items) and rep.accuracy is not None and rep.accuracy < 1.0
    wrong = [i for i in rep.items if i["correct"] is False]
    assert wrong, "the negatives exist to catch a name-only arbiter"
