/* GENERATED by scripts/gen_tokens.py from orchestrator-webapp/app/static/tokens.json — do not edit by hand. */
export const tokens = {
  "color_notes": {
    "brand-bg": "page plane",
    "brand-blue": "categorical slot 1 — links, accents",
    "brand-gray": "secondary ink",
    "brand-green": "status: good (completed)",
    "brand-muted": "muted ink (labels, meta)",
    "brand-red": "status: critical (failed)",
    "brand-serious": "status: serious (needs review)",
    "brand-spark": "status: warning (in-progress)",
    "hairline": "gridline / card border",
    "line": "graph edge / connector line",
    "surface": "card surface"
  },
  "colors": {
    "blue-ink": "#256abf",
    "blue-ink-active": "#1c5cab",
    "blue-wash": "#eef4fc",
    "brand-bg": "#f9f9f7",
    "brand-blue": "#2a78d6",
    "brand-gray": "#52514e",
    "brand-green": "#0ca30c",
    "brand-muted": "#898781",
    "brand-red": "#d03b3b",
    "brand-serious": "#ec835a",
    "brand-spark": "#fab219",
    "green-ink": "#006300",
    "hairline": "#e1e0d9",
    "line": "#c9c8c1",
    "red-ink": "#8a1f1f",
    "serious-ink": "#8a3416",
    "spark-ink": "#7a5200",
    "spark-wash": "#fff3d6",
    "surface": "#fcfcfb"
  },
  "layout": {
    "column_max": "880px",
    "note": "DP phase 2d layout spec 1: one column, read top to bottom, never two."
  },
  "motion": {
    "note": "View Transitions duration; disabled under prefers-reduced-motion.",
    "transition_ms": 160
  },
  "radii": {
    "card": "0.75rem",
    "chip": "0.5rem",
    "dot": "9999px"
  },
  "severities": {
    "blocking": {
      "classes": "text-brand-red",
      "icon": "⚠",
      "label": "blocking"
    },
    "info": {
      "classes": "text-brand-muted",
      "icon": "·",
      "label": "info"
    },
    "warning": {
      "classes": "text-brand-gray",
      "icon": "·",
      "label": "warning"
    }
  },
  "spacing": {
    "card": "1.25rem",
    "gutter": "1.5rem",
    "row": "0.75rem",
    "tight": "0.25rem"
  },
  "tier_notes": "The LABEL is the differentiator (E3-1): every tier reads as its own word, the tint only reinforces it. `unstated` is an explicit gap, shown as such, never blended into the rest. `dot` is the identity hue the Graph view paints beside ink text.",
  "tiers": {
    "asserted": {
      "classes": "bg-brand-spark/15 text-[#7a5200]",
      "dot": "#eda100",
      "label": "asserted"
    },
    "derived": {
      "classes": "bg-brand-blue/10 text-brand-blue",
      "dot": "#1baf7a",
      "label": "derived"
    },
    "observed": {
      "classes": "bg-brand-green/10 text-brand-green",
      "dot": "#2a78d6",
      "label": "observed"
    },
    "stated": {
      "classes": "bg-brand-gray/10 text-brand-gray",
      "dot": "#4a3aa7",
      "label": "stated"
    },
    "unstated": {
      "classes": "bg-brand-red/10 text-brand-red",
      "dot": "#898781",
      "label": "unstated"
    }
  },
  "type_scale": {
    "body": "0.875rem",
    "hero": "1.5rem",
    "meta": "0.75rem",
    "micro": "0.6875rem",
    "title": "1.125rem"
  }
} as const;

export type Tokens = typeof tokens;
export type Tier = keyof Tokens["tiers"];
export type Severity = keyof Tokens["severities"];
export default tokens;
