#!/usr/bin/env python3
"""gen_tokens.py — one tokens.json, two generated consumers (DP phase 2d, Task 1).

The dashboard's look has to exist in two places: the Jinja templates that
FastAPI serves, and the React component library Claude Design compiles. Two
hand-kept copies of a palette drift within a week, so only ONE file is written
by hand — `orchestrator-webapp/app/static/tokens.json` — and this script emits
the other two:

    orchestrator-webapp/app/static/tokens.js   window.PROVLEDGER_TOKENS = {...}
    orchestrator-webapp/design/src/tokens.ts   export const tokens = {...} as const

Both generated files are committed (the Claude Design sync tool reads the
checked-in `design/` tree directly and never runs a build of ours).

    python3 scripts/gen_tokens.py           # write both files
    python3 scripts/gen_tokens.py --check   # exit 1 if either is out of date

`--check` is the test suite's proof that nobody edited tokens.json and forgot
to regenerate — the one failure mode a generated file actually has.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SOURCE = REPO / "orchestrator-webapp" / "app" / "static" / "tokens.json"
JS_OUT = REPO / "orchestrator-webapp" / "app" / "static" / "tokens.js"
TS_OUT = REPO / "orchestrator-webapp" / "design" / "src" / "tokens.ts"

BANNER = ("GENERATED by scripts/gen_tokens.py from "
          "orchestrator-webapp/app/static/tokens.json — do not edit by hand.")


def load(source: Path = SOURCE) -> dict:
    doc = json.loads(source.read_text(encoding="utf-8"))
    return {k: v for k, v in doc.items() if not k.startswith("_")}


def render_js(doc: dict) -> str:
    body = json.dumps(doc, indent=2, ensure_ascii=False, sort_keys=True)
    return (f"/* {BANNER} */\n"
            f"window.PROVLEDGER_TOKENS = {body};\n")


def render_ts(doc: dict) -> str:
    body = json.dumps(doc, indent=2, ensure_ascii=False, sort_keys=True)
    return (f"/* {BANNER} */\n"
            f"export const tokens = {body} as const;\n\n"
            f"export type Tokens = typeof tokens;\n"
            f"export type Tier = keyof Tokens[\"tiers\"];\n"
            f"export type Severity = keyof Tokens[\"severities\"];\n"
            f"export default tokens;\n")


def targets(doc: dict) -> list[tuple[Path, str]]:
    return [(JS_OUT, render_js(doc)), (TS_OUT, render_ts(doc))]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="verify the generated files match tokens.json; write nothing")
    a = ap.parse_args(argv)
    if not SOURCE.exists():
        print(f"gen_tokens: no tokens.json at {SOURCE}", file=sys.stderr)
        return 2
    doc = load()
    stale: list[str] = []
    for path, text in targets(doc):
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        if a.check:
            stale.append(f"{path.relative_to(REPO)} is out of date with tokens.json")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"gen_tokens: wrote {path.relative_to(REPO)}")
    if stale:
        for line in stale:
            print(f"gen_tokens: {line}", file=sys.stderr)
        print("gen_tokens: run `python3 scripts/gen_tokens.py` to regenerate", file=sys.stderr)
        return 1
    if a.check:
        print("gen_tokens: tokens.js and tokens.ts are in sync with tokens.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
