/* build.mjs — esbuild bundles the library into dist/ (DP phase 2d, Task 2).
 *
 * One IIFE bundle with React bundled IN, so a preview card is a single <script>
 * with no import map and no CDN: Claude Design renders the card offline, exactly
 * as the dashboard would. dist/ is committed — the sync tool reads the tree.
 */
import {build} from "esbuild";
import {mkdirSync, writeFileSync, readdirSync, readFileSync} from "node:fs";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const dist = join(here, "dist");
mkdirSync(dist, {recursive: true});

const result = await build({
  entryPoints: [join(here, "src/index.ts")],
  outfile: join(dist, "_ds_bundle.js"),
  bundle: true,
  format: "iife",
  globalName: "ProvLedgerDS",
  platform: "browser",
  target: ["es2020"],
  jsx: "automatic",
  minify: true,
  keepNames: true,
  sourcemap: false,
  legalComments: "none",
  metafile: true,
  logLevel: "info",
});

/* The components style themselves inline from the tokens, so the bundle's CSS
 * is the page-level reset the preview cards need — declared, not empty by
 * accident. */
const tokens = JSON.parse(readFileSync(join(here, "../app/static/tokens.json"), "utf8"));
const vars = Object.entries(tokens.colors).map(([k, v]) => `  --pl-${k}: ${v};`).join("\n");
writeFileSync(join(dist, "_ds_bundle.css"), `/* GENERATED by design/build.mjs */
:root {
${vars}
  --pl-column-max: ${tokens.layout.column_max};
}
*, *::before, *::after { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--pl-brand-bg);
  color: var(--pl-brand-gray);
  font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
  font-size: ${tokens.type_scale.body};
  line-height: 1.55;
}
@media (prefers-reduced-motion: reduce) { * { animation: none !important; transition: none !important; } }
`);

writeFileSync(join(dist, "styles.css"), `/* GENERATED by design/build.mjs — the one stylesheet a preview card links. */
@import "./_ds_bundle.css";
`);

const bytes = result.metafile.outputs[Object.keys(result.metafile.outputs)[0]].bytes;
console.log(`build: dist/_ds_bundle.js ${bytes} bytes · dist/_ds_bundle.css · dist/styles.css`);
console.log(`build: previews ${readdirSync(join(here, "previews")).filter((f) => f.endsWith(".html")).length}`);
